export const BUY_CAKE = "BUY_CAKE";
export const BUY_ICE_CREAM = "BUY_ICE_CREAM";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCESS = "FETCH_USERS_SUCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
